#!/usr/bin/env python3
"""Derive the authoritative Brick / REC / QUDT term lists from Brick.ttl.

The Brick ontology itself is ~10 MB, too large to keep in the repo, so this
script distils it into flat lists the validator can load cheaply.

    pip download --no-deps -d /tmp/bs brickschema
    unzip -q /tmp/bs/brickschema-*.whl -d /tmp/bs/x
    python3 scripts/build_brick_vocab.py /tmp/bs/x/brickschema/ontologies/1.4/Brick.ttl

Writes references/data/brick-vocab.txt - one term per line. A term counts as
known if the ontology either defines it or refers to it; terms marked
`DEPRECATED` or `ALIAS` carry a note with the replacement to use.
"""
import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "references" / "data" / "brick-vocab.txt"

TERM = re.compile(r"^((?:brick|rec|ref|tag):[A-Za-z0-9_.\-]+)\s")
MENTION = re.compile(r"\b((?:unit|brick|rec|ref|tag):[A-Za-z0-9_.\-]+)")


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    ttl = Path(sys.argv[1]).read_text(encoding="utf-8")

    defined, mentioned = set(), set()
    deprecated, alias = {}, {}

    current = None
    for line in ttl.splitlines():
        m = TERM.match(line)
        if m:
            current = m.group(1)
            defined.add(current)
        if current:
            if "owl:deprecated" in line and "true" in line:
                deprecated[current] = ""
            am = re.search(r"brick:aliasOf\s+((?:brick|rec):[A-Za-z0-9_.\-]+)", line)
            if am:
                alias[current] = am.group(1)
            rm = re.search(r"brick:deprecationMitigationMessage\s+\"([^\"]+)\"", line)
            if rm and current in deprecated:
                deprecated[current] = rm.group(1)
        if line.strip() in ("", "."):
            current = None
        mentioned.update(MENTION.findall(line))

    lines = [
        "# Generated by scripts/build_brick_vocab.py from the Brick ontology.",
        "# term<TAB>status<TAB>note   -- status is OK, DEPRECATED or ALIAS",
        "",
    ]
    for term in sorted(defined | mentioned):
        if term in deprecated:
            lines.append(f"{term}\tDEPRECATED\t{deprecated[term]}")
        elif term in alias:
            lines.append(f"{term}\tALIAS\tprefer {alias[term]}")
        else:
            lines.append(f"{term}\tOK\t")
    OUT.write_text("\n".join(lines) + "\n")
    units = {t for t in mentioned if t.startswith("unit:")}
    print(f"{len(defined)} defined terms, {len(mentioned - defined)} referenced-only, "
          f"{len(units)} units, {len(deprecated)} deprecated, {len(alias)} aliases -> {OUT}")


if __name__ == "__main__":
    main()
